### ISSUE TITLE
No License Included In Project

### ISSUE THREAD

**Issue by rtizzy** [coffeehouse-coworkers/coffeehouse-radio#2]
The project is currently unlicensed so standard copyright laws will apply, meaning this project is not currently FOSS (Despite having freely available source). 

If this project is intended to be FOSS, it's suggested that a (FOSS) license be chosen. 

This will help encourage collaboration as it establishes who owns the code and how it may be used. 

You can find more information below. 

http://choosealicense.com/

http://choosealicense.com/no-license/

**Comment by rtizzy** [comment]
Enhancement? I think you mean bug @acoulon99 :tongue:

**Comment by acoulon99** [comment]
It's completely operational without one ;)

**Comment by acoulon99** [comment]
MITed it up!
